

<!DOCTYPE html>

<head>
  <div style="height: 120px">
  </div>
</head>

<body>
    <div id="inner" style="justify-content: center; display: flex; align-items: center;">
        <form style="width: 500px; border: 1px solid black;" action="/downloadplants" method="post">
          <div style="margin:auto; width: 300px;">
            <h1 style="margin:auto; text-align:center;">ERROR</h1>
          </div>
          <br>
          <div style="margin:auto; text-align: center; width: 300px;">
            <input type="button" value="BACK" onclick="history.go(-1)">
          </div>
            <br>
        </form>
    </div>
</body>

<style>
</style>