

<!DOCTYPE html>

<head>
  <div style="height: 120px">
  </div>
</head>

<body>
    <div id="inner" style="justify-content: center; display: flex; align-items: center;">
        <form style="width: 550px; height: 220px; border: 1px solid black;" action="/downloadplants" method="post">
          <div>
            <h1 style="text-align:center;">Error</h1>
            <p style="text-align:center; font-size:17px; font-weight:bold;">ユーザーIDとパスワードが一致しませんでした
            </p>
          </div>
          <br>
          <div style="margin:auto; text-align: center; width: 300px;">
            <input type="button" value="戻る" onclick="history.go(-1)">
          </div>
            <br>
        </form>
    </div>
</body>

<style>
</style>