<!DOCTYPE html>

<head>
  <link rel="icon" href="#">
  <div style="height: 120px">
  </div>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>CSV Download Tool</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>

    $(document).ready(function(){
      $( function() {
        $( "#dateFrom" ).datepicker({ dateFormat: 'yy-mm-dd' });
        $( "#dateTo" ).datepicker({ dateFormat: 'yy-mm-dd' });
      } );
    });

    function fillDatePicker() {
      var date = new Date();

      var prevMonthStart = (new Date(date.getFullYear(), date.getMonth()-1,2)).toISOString().split('T')[0];
      var prevMonthEnd = (new Date(date.getFullYear(), date.getMonth())).toISOString().split('T')[0];

      $("#dateFrom").val(prevMonthStart);
      $("#dateTo").val(prevMonthEnd);
    }

    function selectAllSites() {
      $("#plants").attr("data-select", "true").find("option").prop("selected", true);
    }
      
    function formatDate(date) {
      var d = new Date(date),
          month = '' + (d.getMonth() + 1),
          day = '' + d.getDate(),
          year = d.getFullYear();

      if (month.length < 2) 
          month = '0' + month;
      if (day.length < 2) 
          day = '0' + day;

      return [year, month, day].join('-');
    }
    
    function downloadFiles(){
      var plants = $('#plants').val();

      var dateFromUTCFormat = $('#dateFrom').datepicker('getDate');
      var dateFromString = formatDate(dateFromUTCFormat);

      var dateToUTCFormat = $('#dateTo').datepicker('getDate');
      var dateToStringForFilename = formatDate(dateToUTCFormat);
      var newDateToUTCFormat = new Date(dateToUTCFormat);
      newDateToUTCFormat.setDate(dateToUTCFormat.getDate() + 1);
      var dateToString = formatDate(newDateToUTCFormat);

      if (!plants) {
        $('#plantLabel').css("color", "red");
        return;
      }
      else
        $('#plantLabel').css("color", "black");


      if ((!dateFromUTCFormat) || (!dateToUTCFormat)) {
        $('#dateLabel').css("color", "red");
        return;
      }
      else
        $('#dateLabel').css("color", "black");

      var plantNames = [];

      for (var i = 0; i < plants.length; i++) {

        var plantName;

        if (plants[i].includes('https://ichigo.sp-viewer.net/')) {
          var plantNameWithSlash = plants[i].replace('https://ichigo.sp-viewer.net/', '');
          plantName = plantNameWithSlash.replace('/', '');
        }
        else if (plants[i].includes('http://219.127.165.30/')) {
          plantName = "kure";
        }

        plantNames.push(plants[i] + "ac/download_measurement.php?freq=daily&target_date_ge=" + dateFromString + "&target_date_lt=" +
            dateToString + "&format=csv&table=" + plantName + "_" + dateFromString + "_" + dateToStringForFilename);

      }

      downloadFilesSimultaneously(plantNames);
    }

    function downloadFilesSimultaneously(files){
      for (var i = 0; i < files.length; i++) {
        var f = files[i];
        if (files[i].includes('http://219.127.165.30/')) {
          var urlToSend = files[i];
          window.open(files[i]);
          // setTimeout(function(){
          //   alert(5);
          // },15000); 

          // const link = document.createElement('a');
          // link.href = files[i];
          // link.target = '_blank';
          // document.body.appendChild(link);
          // link.click();   
          // link.remove(); 
         
          // var url = files[i];
          // setTimeout(function(){
          //   // window.open(url, '_blank').focus();
          // },5000); 

          // req.open("GET", urlToSend, true);
          // req.responseType = "blob";
          // req.onload = function (event) {
              // var fileName = "fileName"; //if you have the fileName header available
              // var link=document.createElement('a');
              // link.href=window.URL.createObjectURL(urlToSend);
              // link.download=fileName;
              // link.click();
          // };

          // req.send();

        }
        else {
          window.open(files[i], '_blank').focus();
        }
      }
}

  </script>
</head>

<body>
    <div id="inner" style="justify-content:center; display:flex; align-items:center;">
      <div style="border:1px solid black;">
            <div style="margin:auto; width:300px;">
              <h1 style="margin:auto; text-align:center;">PLANT REPORT</h1>
            </div>
            <br>
            <div style="margin-left:70px; width:300px;">
              <label id="plantLabel">拠点選択：</label>
                <select name="plants" id="plants" multiple>
                  <optgroup label="IGI">
                    <?php foreach ($plants as $plant) { ?>
                      <option value="<?= $plant['plant_uri']; ?>" selected><?= $plant['plant_name'] ?></option>
                    <?php } ?>
                  </optgroup>
                  <optgroup label="IEE">
                    <?php foreach ($plantsNonG as $plant) { ?>
                      <option value="<?= $plant['plant_uri']; ?>" selected><?= $plant['plant_name'] ?></option>
                    <?php } ?>
                  </optgroup>
                  <input style="margin-left:5px; vertical-align:middle; " type="button" value="全部" name="selectAll" onclick=selectAllSites()>
                </select>
            </div>
            <div style="font-size:10px; margin:auto; margin-left:70px;">
              <br>
              Ctrl（Windows）またはCommand（Mac）ボタンを押したままにして
              <br>
              複数のオプションを選択します
            </div>
            <br>
            <div style="margin-left:70px; width: 400px;">
              <label id="dateLabel">期間選択：</label>
              <input style="vertical-align:middle; width:80px" type="text" id="dateFrom" name="dateFrom"> ~ 
              <input style="vertical-align:middle; width:80px" type="text" id="dateTo" name="dateTo">
              <input style="margin-left:20px; vertical-align:middle; " type="button" value="前月" name="previous" onclick=fillDatePicker()>
            </div>
            <br>
            <div style="margin:auto; text-align:center; width:300px;">
              <button onclick="downloadFiles()">ダウンロード</button>
            </div>
            <div style="font-size:10px; margin:auto; margin-left:110px;">
              <br>
              *複数のレポートをダウンロードできない場合は、
              <br>
              ブラウザのポップアップブロッカーを無効にしてください。
            </div>
            <br>
      </div>
    </div>


</body>

<style>
  #inner {
    /* padding: 50px 0px 60px 170px; */
    /* padding-left: 30px; */
    /* padding-top: 30px; */
    /* padding-bottom: 30px; */
    /* display: table; */
    /* margin: auto; */
  }

  .dropbtn {
    background-color: #3498DB;
    color: white;
    padding: 16px;
    font-size: 16px;
    border: none;
    cursor: pointer;
  }

  /* Dropdown button on hover & focus */
  .dropbtn:hover, .dropbtn:focus {
    background-color: #2980B9;
  }

  /* The container <div> - needed to position the dropdown content */
  .dropdown {
    position: relative;
    display: inline-block;
  }

  /* Dropdown Content (Hidden by Default) */
  .dropdown-content {
    display: none;
    position: absolute;
    background-color: #f1f1f1;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
  }

  /* Links inside the dropdown */
  .dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
  }

  /* Change color of dropdown links on hover */
  .dropdown-content a:hover {background-color: #ddd}

  /* Show the dropdown menu (use JS to add this class to the .dropdown-content container when the user clicks on the dropdown button) */
  .show {display:block;}

</style>