<!-- <!DOCTYPE html>

<head>
  <link rel="icon" href="#">
  <div style="height: 120px">
  </div>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>拠点CSVダウンロード</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  alert('hello');
  </script>
</head>


<body>
    <div id="inner" style="justify-content:center; display:flex; align-items:center;">
      <div class="container" style="border:1px solid black;">
              <h1 style="text-align:center;">拠点CSVログイン</h1>
            <div class="style-1">
                <label for="uname"><b>Username:</b></label>
                <input type="text" placeholder="Enter Username" name="uname" required>
                <br><br>
                <label for="psw"><b>Password:</b></label>
                <input type="password" placeholder="Enter Password" name="psw" required>
                <br><br><br>
                <button type="submit">ダウンロード</button>
            </div>
      </div>
    </div>
</body>

<style>
.container {
    text-align: center;
    width: 400px;
    height: 230px;
}
.style-1 {
    font-size: 15px;
}
</style> -->

<!DOCTYPE html>

<head>
  <link rel="icon" href="#">
  <div style="height: 120px">
  </div>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>CSV Download Tool</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <!-- <script src="https://code.jquery.com/jquery-1.12.4.js"></script> -->
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script>

    $(document).ready(function(){
		$("#myModal").modal('show');
	});

    $(document).ready(function(){
      $( function() {
        $( "#dateFrom" ).datepicker({ dateFormat: 'yy-mm-dd' });
        $( "#dateTo" ).datepicker({ dateFormat: 'yy-mm-dd' });
      } );
    });

    function fillDatePicker() {
      var date = new Date();

      var prevMonthStart = (new Date(date.getFullYear(), date.getMonth()-1,2)).toISOString().split('T')[0];
      var prevMonthEnd = (new Date(date.getFullYear(), date.getMonth())).toISOString().split('T')[0];

      $("#dateFrom").val(prevMonthStart);
      $("#dateTo").val(prevMonthEnd);
    }
      
    function formatDate(date) {
      var d = new Date(date),
          month = '' + (d.getMonth() + 1),
          day = '' + d.getDate(),
          year = d.getFullYear();

      if (month.length < 2) 
          month = '0' + month;
      if (day.length < 2) 
          day = '0' + day;

      return [year, month, day].join('-');
    }
    
    function downloadFiles(){
      var plants = $('#plants').val();

      var dateFromUTCFormat = $('#dateFrom').datepicker('getDate');
      var dateFromString = formatDate(dateFromUTCFormat);

      var dateToUTCFormat = $('#dateTo').datepicker('getDate');
      var dateToString = formatDate(dateToUTCFormat);

      if (!plants) {
        $('#plantLabel').css("color", "red");
        return;
      }
      else
        $('#plantLabel').css("color", "black");


      if ((!dateFromUTCFormat) || (!dateToUTCFormat)) {
        $('#dateLabel').css("color", "red");
        return;
      }
      else
        $('#dateLabel').css("color", "black");

      var plantNames = [];

      for (var i = 0; i < plants.length; i++) {

        var plantName;

        if (plants[i].includes('https://ichigo.sp-viewer.net/')) {
          var plantNameWithSlash = plants[i].replace('https://ichigo.sp-viewer.net/', '');
          plantName = plantNameWithSlash.replace('/', '');
        }
        else if (plants[i].includes('http://219.127.165.30/')) {
          plantName = "kure";
        }

        plantNames.push(plants[i] + "ac/download_measurement.php?freq=daily&target_date_ge=" + dateFromString + "&target_date_lt=" +
            dateToString + "&format=csv&table=" + plantName + "_" + dateFromString + "_" + dateToString);
      }

      downloadFilesSimultaneously(plantNames);
      // download_files(files);
    }

    function downloadFilesSimultaneously(files){
      for (var i = 0; i < files.length; i++) {
        console.log('downloading: ' + files[i]);
        window.open(files[i], '_blank').focus();
      }
    }

    function opacityChange() {
       
        $("#inner").css('opacity', '1');
       $("#myModal").modal('hide');
 
    }

    // function clickChange() {
    //     $("body").css('background', 'blue');
    // }

  </script>
</head>

<body>

    <!-- <div class="popup-login">

    </div> -->

    <div class="bs-example">
    <div id="myModal" class="modal fade" tabindex="-1">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Confirmation</h5>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <p>Do you want to save changes to this document before closing?</p>
                        <p class="text-secondary"><small>If you don't save, your changes will be lost.</small></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button onclick="opacityChange()" type="button" class="btn btn-primary">Save changes</button>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div id="inner" style="justify-content:center; display:flex; align-items:center;">
      <div style="border:1px solid black;">
            <div style="margin:auto; width:300px;">
              <h1 style="margin:auto; text-align:center;">PLANT REPORT</h1>
            </div>
            <br>
            <div style="margin-left:70px; width:300px;">
              <label id="plantLabel">拠点選択：</label>
                <select name="plants" id="plants" multiple>
                  <optgroup label="IGI">
                    <?php foreach ($plants as $plant) { ?>
                      <option value="<?= $plant['plant_uri']; ?>"><?= $plant['plant_name'] ?></option>
                    <?php } ?>
                  </optgroup>
                  <optgroup label="IEE">
                    <?php foreach ($plantsNonG as $plant) { ?>
                      <option value="<?= $plant['plant_uri']; ?>"><?= $plant['plant_name'] ?></option>
                    <?php } ?>
                  </optgroup>
                </select>
            </div>
            <div style="font-size:10px; margin:auto; margin-left:70px;">
              <br>
              Ctrl（Windows）またはCommand（Mac）ボタンを押したままにして
              <br>
              複数のオプションを選択します
            </div>
            <br>
            <div style="margin-left:70px; width: 400px;">
              <label id="dateLabel">期間選択：</label>
              <input style="vertical-align:middle; width:80px" type="text" id="dateFrom" name="dateFrom"> ~ 
              <input style="vertical-align:middle; width:80px" type="text" id="dateTo" name="dateTo">
              <input style="margin-left:20px; vertical-align:middle; " type="button" value="前月" name="previous" onclick=fillDatePicker()>
            </div>
            <br>
            <div style="margin:auto; text-align:center; width:300px;">
              <button onclick="downloadFiles()">ダウンロード</button>
            </div>
            <br>
      </div>
    </div>


</body>

<style>
  #inner {
    opacity:0;
  }

  .dropbtn {
    background-color: #3498DB;
    color: white;
    padding: 16px;
    font-size: 16px;
    border: none;
    cursor: pointer;
  }

  /* Dropdown button on hover & focus */
  .dropbtn:hover, .dropbtn:focus {
    background-color: #2980B9;
  }

  /* The container <div> - needed to position the dropdown content */
  .dropdown {
    position: relative;
    display: inline-block;
  }

  /* Dropdown Content (Hidden by Default) */
  .dropdown-content {
    display: none;
    position: absolute;
    background-color: #f1f1f1;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
  }

  /* Links inside the dropdown */
  .dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
  }

  /* Change color of dropdown links on hover */
  .dropdown-content a:hover {background-color: #ddd}

  /* Show the dropdown menu (use JS to add this class to the .dropdown-content container when the user clicks on the dropdown button) */
  .show {display:block;}

</style>